#!/usr/bin/env python3
"""Generate Wiggins' Android vector drawables from design/wiggins.svg.

  python3 design/make_drawables.py

Writes, under app/src/main/res/drawable/:
  wiggins_figure.xml          the figure alone (amber), 200x200 viewport, composed for a
                              circle or hexagon frame; the app draws bubbles over it
  ic_launcher_foreground.xml  figure and resting bubbles, fitted to the adaptive icon's
                              circular mask (72dp of the 108dp canvas)
  ic_launcher_monochrome.xml  the same shapes in one color, for themed icons
"""
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SVG = (ROOT / "design/wiggins.svg").read_text()
OUT = ROOT / "app/src/main/res/drawable"
AMBER, NAVY = "#F9BC4D", "#1B2440"
# Where the figure sits in its 200x200 frame (balanced inside a circle or hexagon).
COMPOSE = 'android:translateX="9" android:translateY="14" android:scaleX="0.93" android:scaleY="0.93"'
HEADER = '<?xml version="1.0" encoding="utf-8"?>\n<!-- Generated by design/make_drawables.py from design/wiggins.svg; edit those instead. -->\n'


def circle(cx, cy, r):
    return f"M {cx - r},{cy} a {r},{r} 0 1,0 {2 * r},0 a {r},{r} 0 1,0 {-2 * r},0"


def figure_paths(color):
    fill = re.search(r'<g fill="#1B2440">(.*?)</g>', SVG, re.S).group(1)
    out = [f'<path android:fillColor="{color}" android:pathData="{" ".join(d.split())}" />'
           for d in re.findall(r'<path d="([^"]+)"', fill)]
    stem = re.search(r'stroke-width="4" stroke-linecap="round" d="([^"]+)"', SVG).group(1)
    out.append(f'<path android:strokeColor="{color}" android:strokeWidth="4" android:strokeLineCap="round" android:pathData="{stem}" />')
    return out


def bubble_paths(color):
    bubbles = re.search(r'<g fill="none" stroke="#1B2440" stroke-width="3">(.*?)</g>', SVG, re.S).group(1)
    shapes = [circle(*map(float, c)) for c in re.findall(r'<circle cx="([\d.]+)" cy="([\d.]+)" r="([\d.]+)"/>', bubbles)]
    shapes += re.findall(r'stroke-linejoin="round" d="([^"]+)"', bubbles)
    out = [f'<path android:strokeColor="{color}" android:strokeWidth="3" android:strokeLineJoin="round" android:pathData="{d}" />' for d in shapes]
    glints = re.search(r'stroke-width="2" stroke-linecap="round">(.*?)</g>', SVG, re.S).group(1)
    out += [f'<path android:strokeColor="{color}" android:strokeWidth="2" android:strokeLineCap="round" android:pathData="{d}" />'
            for d in re.findall(r'<path d="([^"]+)"/>', glints)]
    return out


def vector(size, viewport, body):
    return (HEADER + f'<vector xmlns:android="http://schemas.android.com/apk/res/android"\n'
            f'    android:width="{size}dp" android:height="{size}dp"\n'
            f'    android:viewportWidth="{viewport}" android:viewportHeight="{viewport}">\n{body}</vector>\n')


def group(attrs, items, indent="    "):
    inner = "".join(f"{indent}    {i}\n" for i in items)
    return f"{indent}<group {attrs}>\n{inner}{indent}</group>\n"


(OUT / "wiggins_figure.xml").write_text(vector(48, 200, group(COMPOSE, figure_paths(AMBER))))
# The 200x200 frame's circle (r 96) maps onto the 72dp mask: scale 36/96, centered on 54.
ICON = 'android:translateX="16.5" android:translateY="16.5" android:scaleX="0.375" android:scaleY="0.375"'
for name, color in (("ic_launcher_foreground", AMBER), ("ic_launcher_monochrome", "#FF000000")):
    inner = group(COMPOSE, figure_paths(color) + bubble_paths(color), indent="        ")
    (OUT / f"{name}.xml").write_text(vector(108, 108, f'    <group {ICON}>\n{inner}    </group>\n'))
print("wrote", ", ".join(p.name for p in sorted(OUT.glob("*wiggins*")) + [OUT / "ic_launcher_foreground.xml", OUT / "ic_launcher_monochrome.xml"]))
